### ISSUE TITLE
Advanced permissions

### ISSUE THREAD

**Issue by guyzmo** [biosustain/flask-presst#13]
Hi,

I'd like to create a fine grained permissions system that can filter out data from the output for a given user. As an example, let's consider `User`s, `Group`s and `Item`s. An `User` and an `Item` are related to a `Group`:

```
     
     ┌───────┐             ┌───────┐             ┌───────┐
     │ Item  │             │ Group │             │ User  │
     ├───────┤             ├───────┤             ├───────┤
     │ id    │       ┌────>│ id    │<──────┐     │ id    │
     │ name  │       │     │ name  │       │     │ name  │
     │ group ├───────┘     └───────┘       └─────┤ group │
     └───────┘                                   │ role  │
                                                 └───────┘
```

So here we have two kinds of role that are being used, `admin` and `user`. If `admin`
is being used, the default Role is right. But if `user` is used, I'd like to filter
the results out based on the `User↔Item` relation based on the `group` field (i.e.
get all items for `User→group==Item→group`).

I guess I have to subclass `PrincipalResource`, and I'm already looking into that,
but before starting the code, I'm open to any advices so I can be on the right track,
and maybe even consider send that subclass as a patch?

**Comment by lyschoening** [comment]
@guyzmo Not sure if you are still using Flask-Presst, but here's a heads-up: [Flask-Potion](https://github.com/biosustain/potion) has been released so I will not develop Flask-Presst any further.

**Comment by guyzmo** [comment]
interesting, I'm not currently active on the project where I needed it, but is the transition from the former straightforward? But good news you're going further ;-)

**Comment by lyschoening** [comment]
It is relatively easy to migrate the code. However, the way relations work by default has changed and that may require some effort on the client side.
