### ISSUE TITLE
Creating beautiful routes

### ISSUE THREAD

**Issue by svenstaro** [biosustain/flask-presst#3]
I would to have a somewhat deeply nested Resource a path such as /cities/London/streets/51314/buildings/131/apartments/1241

From the docs, it's not entirely obvious to me how to accomplish this using flask-presst. The Relationship thingies don't appear to be generating such beautiful paths but rather prefer a flat structure which in my application doesn't make sense.

**Comment by lyschoening** [comment]
@svenstaro I have abandoned this project and released a replacement, [Flask-Potion](https://github.com/biosustain/potion). It's currently in a beta state. Routes for joins are not in Potion's philosophy, so this issue won't be addressed there either. Potion no longer uses Flask-RESTful internally, so it might be less interesting for you (though it possibly has some features that could be brought back into RESTful).
